{% set name = "neattext" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/neattext-{{ version }}.tar.gz
  sha256: 23a44ea946024bbde20487ba05a82a8c963cee4cefba40c138dc8076fc18792e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - poetry >=0.12
    - python {{ python_min }}
  run:
    - python >={{ python_min }},<4.0

test:
  imports:
    - neattext
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Jcharis/neattext
  doc_url: https://jcharis.github.io/neattext/
  summary: A simple NLP package for cleaning text
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
